services:
#  phpmyadmin:
#    image: phpmyadmin
#    container_name: mysql-admin
#    ports:
#      - 9999:80
#    environment:
#      - PMA_HOST=mysql
#    networks:
#      - mysql-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - mysql-network
    volumes:
      - D:/game/dockerdata/mysql:/tmp

networks:
  mysql-network:
    name: mysql-network
    driver: bridge
