#!/bin/sh

PW_PATH=/root

if [ ! -d $PW_PATH/logs ]; then
    mkdir $PW_PATH/logs
else
    rm $PW_PATH/logs/*.log
fi

service mariadb start
service apache2 start

if [ -n "$1" ]; then

    echo "=== LOGSERVICE ======"
    cd $PW_PATH/logservice
    ./logservice logservice.conf > $PW_PATH/logs/logservice.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== UNIQUENAMED ====="
    cd $PW_PATH/uniquenamed
    ./uniquenamed gamesys.conf > $PW_PATH/logs/uniquenamed.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== AUTH ============"
    cd $PW_PATH/authd/
    ./authd > $PW_PATH/logs/authd.log &
    sleep 3
    echo "=== DONE! ==========="
    echo ""

    echo "=== GAMEDBD ========="
    cd $PW_PATH/gamedbd
    ./gamedbd gamesys.conf > $PW_PATH/logs/gamedbd.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GACD ============"
    cd $PW_PATH/gacd
    ./gacd gamesys.conf > $PW_PATH/logs/gacd.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GFACTIOND ======="
    cd $PW_PATH/gfactiond
    ./gfactiond gamesys.conf > $PW_PATH/logs/gfactiond.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GDELIVERYD ======"
    cd $PW_PATH/gdeliveryd
    ./gdeliveryd gamesys.conf > $PW_PATH/logs/gdeliveryd.log &
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GLINKD =========="
    cd $PW_PATH/glinkd
    ./glinkd gamesys.conf 1 > $PW_PATH/logs/glink.log &
    ./glinkd gamesys.conf 2 > $PW_PATH/logs/glink2.log &
    ./glinkd gamesys.conf 3 > $PW_PATH/logs/glink3.log &
    ./glinkd gamesys.conf 4 > $PW_PATH/logs/glink4.log &
    sleep 3
    echo "=== DONE! ==========="
    echo ""

    echo "=== LOAD MAPS ======="
    cd $PW_PATH/gamed
    ./gs gs01 > $PW_PATH/logs/game1.log &
    ./gs is61 > $PW_PATH/logs/game1.log &
    ./gs is69 > $PW_PATH/logs/game1.log &
    echo "=== DONE! ==========="
    echo ""

else

    echo "=== LOGSERVICE ======"
    cd $PW_PATH/logservice
    nohup ./logservice logservice.conf > $PW_PATH/logs/logservice.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== UNIQUENAMED ====="
    cd $PW_PATH/uniquenamed
    nohup ./uniquenamed gamesys.conf > $PW_PATH/logs/uniquenamed.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== AUTH ============"
    cd $PW_PATH/authd/
    nohup ./authd > $PW_PATH/logs/authd.log 2>&1
    sleep 3
    echo "=== DONE! ==========="
    echo ""

    echo "=== GAMEDBD ========="
    cd $PW_PATH/gamedbd
    nohup ./gamedbd gamesys.conf > $PW_PATH/logs/gamedbd.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GACD ============"
    cd $PW_PATH/gacd
    nohup ./gacd gamesys.conf > $PW_PATH/logs/gacd.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GFACTIOND ======="
    cd $PW_PATH/gfactiond
    nohup ./gfactiond gamesys.conf > $PW_PATH/logs/gfactiond.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GDELIVERYD ======"
    cd $PW_PATH/gdeliveryd
    nohup ./gdeliveryd gamesys.conf > $PW_PATH/logs/gdeliveryd.log 2>&1
    sleep 2
    echo "=== DONE! ==========="
    echo ""

    echo "=== GLINKD =========="
    cd $PW_PATH/glinkd
    nohup ./glinkd gamesys.conf 1 > $PW_PATH/logs/glink.log 2>&1
    nohup ./glinkd gamesys.conf 2 > $PW_PATH/logs/glink2.log 2>&1
    nohup ./glinkd gamesys.conf 3 > $PW_PATH/logs/glink3.log 2>&1
    nohup ./glinkd gamesys.conf 4 > $PW_PATH/logs/glink4.log 2>&1
    sleep 3
    echo "=== DONE! ==========="
    echo ""

    echo "=== LOAD MAPS ======="
    cd $PW_PATH/gamed
    nohup ./gs gs01 > $PW_PATH/logs/game1.log 2>&1
    nohup ./gs is61 > $PW_PATH/logs/game1.log 2>&1
    nohup ./gs is69 > $PW_PATH/logs/game1.log 2>&1
    echo "=== DONE! ==========="
    echo ""

fi

echo "=== WEB TOOLS ======="
$PW_PATH/server pwAdmin start
