#!/bin/bash

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

PW_PATH=/root

function loadMaps(){

    local maps=$1

    IFS=',' read -r -a mapList <<< "$maps"
    for map in "${mapList[@]}"; do
        "${PW_PATH}"/server start-map ${map}
    done

}

function main(){

    echo "Script started!"
    trap 'echo "Script ended!"' EXIT

    service mariadb start

    "${PW_PATH}"/server clearlogs

    "${PW_PATH}"/server start no-maps

    loadMaps "gs01,is61,is69"

    sleep 40
    echo "=== WEB TOOLS ======="
    nohup sh -c "JAVA_HOME=${PW_PATH}/jdk1.6.0_45 /home/tomcat/bin/catalina.sh run" &

}

# run the script
main
