#!/bin/bash

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

PW_PATH=/root
LogsPath="${PW_PATH}/logs"

function clearLog(){
    if [ ! -d $LogsPath ]; then
        mkdir $LogsPath
    else
        rm $LogsPath/*
    fi
}

function startAuthd() {

    echo "##############################  - Enable account data service (AUTHD) ####################"
    # Account Data Service
    cd "${PW_PATH}"/authd/
    nohup ./authd 2>&1 | tee $LogsPath/authd.log &
    sleep 2
    AU=`ps -ef | grep authd | grep -v grep | awk '{print $2}'`
    if [ "$AU" != "" ]; then
        echo "Account data service started successfully!"
    else
        echo "Account data service startup failed!"
    fi
    echo ""
}

function startGamedbd(){

    echo "##############################  - Start the role data service(GAMEDBD) ##################"
    # Role Data Service #
    cd "${PW_PATH}"/gamedbd/
    nohup ./gamedbd gamesys.conf 2>&1 | tee $LogsPath/gamedbd.log &
    sleep 2
    DB=`ps -ef | grep gamedbd | grep -v grep | awk '{print $2}'`
    if [ "$DB" != "" ]; then
       echo "The role data service started successfully!"
    else
       echo "Role data service started failed!"
    fi
    echo ""
}

function startGacd(){

    echo "##############################  - Start anti-addiction service(GACD) ####################"
    # Anti-addiction service #
    cd "${PW_PATH}"/gacd/
    nohup ./gacd gamesys.conf 2>&1 | tee $LogsPath/gacd.log &
    sleep 2
    GACD=`ps -ef | grep gacd | grep -v grep | awk '{print $2}'`
    if [ "$GACD" != "" ]; then
        echo "The anti-addiction service started successfully!"
    else
        echo "Anti-addiction service started failed!"
    fi
    echo ""
}

function startUniquenamed(){

    echo "##############################  - Start the Unique Name service(UNIQUENAMED) ############"
    # Unique Name service #
    cd "${PW_PATH}"/uniquenamed
    nohup ./uniquenamed gamesys.conf 2>&1 | tee $LogsPath/uniquename.log &
    sleep 2
    UN=`ps -ef | grep uniquenamed | grep -v grep | awk '{print $2}'`
    if [ "$UN" != "" ]; then
       echo "Unique Name service started successfully!"
    else
       echo "Unique Name service started failed!"
    fi
    echo ""
}

function startGfactiond(){

    echo "##############################  - Start the Gang service(GFACTIOND) #####################"
    # Gang Service #
    cd "${PW_PATH}"/gfactiond/
    nohup ./gfactiond gamesys.conf 2>&1 | tee $LogsPath/gfactiond.log &
    sleep 2
    GF=`ps -ef | grep gfactiond | grep -v grep | awk '{print $2}'`
    if [ "$GF" != "" ]; then
       echo "Gang service started successfully!"
    else
       echo "Gang service started failed!"
    fi
    echo ""
}

function startLogservice(){

    echo "##############################  - Start the Log service #################################"
    # Log Service #
    cd "${PW_PATH}"/logservice
    nohup ./logservice logservice.conf 2>&1 | tee $LogsPath/logservice.log &
    sleep 2
    LOGS=`ps -ef | grep logservice | grep -v grep | awk '{print $2}'`
    if [ "$LOGS" != "" ]; then
       echo "The Log service started successfully!"
    else
       echo "The Log service started failed!"
    fi
    echo ""
}

function startGlinkd(){

    echo "##############################  - Start the Login relation service(GLINKD) ##############"
    # Login relation Service #
    cd "${PW_PATH}"/glinkd/
    nohup ./glinkd gamesys.conf 1 2>&1 | tee $LogsPath/glinkd1.log &
    nohup ./glinkd gamesys.conf 2 2>&1 | tee $LogsPath/glinkd2.log &
    nohup ./glinkd gamesys.conf 3 2>&1 | tee $LogsPath/glinkd3.log &
    nohup ./glinkd gamesys.conf 4 2>&1 | tee $LogsPath/glinkd4.log &
    sleep 1
    LINK=`ps -ef | grep glinkd | grep -v grep | awk '{print $2}'`
    if [ "$LINK" != "" ]; then
       echo "Login relation service started successfully!"
    else
       echo "Login relation service started failed!"
    fi
    echo ""
}

function loadMaps(){

    maps="gs01,is61,is69"

    echo "##############################  - Load Maps(GS) #########################################"
    cd "${PW_PATH}"/gamed/
    nohup ./gs gs01 >/home/logs/gs01.log 2>&1 &
    sleep 2
    nohup ./gs is61 >/home/logs/is61.log 2>&1 &
    sleep 2
    nohup ./gs is69 >/home/logs/is69.log 2>&1 &
    sleep 2
    #IFS=',' read -r -a mapList <<< "$maps"
    #for map in "${mapList[@]}"; do
    #    nohup ./gs "$map" > "${PW_PATH}/logs/$map.log" 2>&1 &
    #    sleep 2
    #    GS=`ps -ef | grep gs | grep -v grep | awk '{print $2}'`
    #    if [ "$GS" != "" ]; then
    #       echo "The map $map loaded successfully!"
    #    else
    #       echo "The map $map loaded failed!"
    #    fi
    #done

}

function startGdeliveryd(){

    echo "##############################  - Start basic service(GDELIVERYD) #######################"
    # Basic Services #
    cd "${PW_PATH}"/gdeliveryd/
    nohup ./gdeliveryd gamesys.conf 2>&1 | tee $LogsPath/gdeliveryd.log &
    sleep 2
    GD=`ps -ef | grep gdeliveryd | grep -v grep | awk '{print $2}'`
    if [ "$GD" != "" ]; then
       echo "Basic service started successfully!"
    else
       echo "Basic service started failed!"
    fi
    echo ""
}

function startWebTools(){

    echo "=== WEB TOOLS ======="
    "${PW_PATH}"/server pwAdmin start

}

function main(){

    echo "##############################   Server starting!  ######################################"
    trap 'echo "Script end!"' EXIT

    service mariadb start

    clearLog
    startAuthd
    startGamedbd
    startGacd
    startUniquenamed
    startGfactiond
    startLogservice
    loadMaps
    startGdeliveryd
    startGlinkd

    second=30
    echo "Wait $second second for stable..."
    sleep $second
    startWebTools

}


