#!/bin/bash

PW_PATH=/home

echo "##############################  - Load Maps(GS) #########################################"
cd "${PW_PATH}"/gamed/
nohup ./gs gs01 > "${PW_PATH}"/logs/gs01.log &
nohup ./gs is61 > "${PW_PATH}"/logs/is61.log &

echo "Log files should be generated."
echo "If you see the error: ./gs: No such file or directory, please re-check the C++ libraries installation step."
echo ""