#!/bin/bash

PW_PATH=/home

echo "##############################  - Enable Authentication service (AUTHD) ####################"
cd "${PW_PATH}"/authd/
nohup ./authd 2>&1 | tee ${PW_PATH}/logs/authd.log &
sleep 2
AU=`ps -ef | grep authd | grep -v grep | awk '{print $2}'`
if [ "$AU" != "" ]; then
    echo "Authentication service started successfully!"
else
    echo "Authentication service started failed!"
fi
echo ""